import "./globals.css";
import { Rationale, Montserrat_Alternates, Michroma } from "next/font/google";
import Header from "./layout/header/Header";
import Footer from "./layout/footer/Footer";
import {hasLocale, NextIntlClientProvider} from "next-intl"
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";

const rationale = Rationale({
  variable: "--font-rationale",
  subsets: ["latin"],
  weight: "400",
});

const michroma = Michroma({
  variable: "--font-michroma",
  weight: '400',
  subsets: ['latin'],
})

const montserratAlternates = Montserrat_Alternates({
  variable: "--font-montserrat-alternates",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang="en">
      <body
        className={`${rationale.variable} ${montserratAlternates.variable} ${michroma.variable} antialiased text-gold min-h-screen flex flex-col`}
      >
       <NextIntlClientProvider>
         <Header />
           {children}
          <Footer />
       </NextIntlClientProvider>
      </body>
    </html>
  );
}
